HOME_DIR="/home/$(whoami)"
INSTALL_DIR="${HOME_DIR}/.cache/dein/repos/github.com/Shougo/dein.vim"

echo ""
echo "\"dein Scripts-----------------------------"
echo "if &compatible"
echo "  set nocompatible               \" Be iMproved"
echo "endif"
echo ""
echo "\" Required:"
echo "set runtimepath+=$INSTALL_DIR"
echo ""
echo "\" Required:"
echo "if dein#load_state('$HOME_DIR/.cache/dein')"
echo "  call dein#begin('$HOME_DIR/.cache/dein')"
echo ""
echo "  \" Let dein manage dein"
echo "  \" Required:"
echo "  call dein#add('$INSTALL_DIR')"
echo ""
echo "  \" Add or remove your plugins here like this:"
echo "  \"call dein#add('Shougo/neosnippet.vim')"
echo "  \"call dein#add('Shougo/neosnippet-snippets')"
echo ""
echo "  \" Required:"
echo "  call dein#end()"
echo "  call dein#save_state()"
echo "endif"
echo ""
echo "\" Required:"
echo "filetype plugin indent on"
echo "syntax enable"
echo ""
echo "\" If you want to install not installed plugins on startup."
echo "\if dein#check_install()"
echo "\  call dein#install()"
echo "\endif"
echo ""
echo "\"End dein Scripts-------------------------"
echo ""
